### ISSUE TITLE
Messages confirmed but not delivered

### ISSUE THREAD

**Issue by uberdave** [KevinGoodsell/tmda-fork#10]
I get the confirmation requested and the confirmation approved emails, but never get the message.
tmda regular script-not cgi
debian jessie
qmail
vpopmail
courier imap

**Comment by pjz** [comment]
I have no way to test this; I mostly just forward-ported this to a sane version of python.  That said, I suggest enabling all possible logging/debugging and seeing what you can figure out.  Sorry if that's not much help :(

**Comment by uberdave** [comment]
understood. thank you
