### ISSUE TITLE
Doesn't work for tmda-cgi

### ISSUE THREAD

**Issue by BigBaaadBob** [KevinGoodsell/tmda-fork#8]
This is stated in the Wiki.  I'm putting an issue here so that it might eventually get resolved.

**Comment by KevinGoodsell** [comment]
I spent some time trying to figure out exactly why I claim tmda-cgi won't work. The only definite issue I came up with is that it uses the pythonlib/email module which I removed from this repository. Beyond that it still uses some deprecated modules, and it uses Auth.py, which is mostly copy/pasted from the old tmda-ofmipd authentication code and may not be strictly compatible with the newer authentication code (certainly it doesn't support the new PAM authentication). I don't know whether this is important, though.

The plan is to try to get this all working, remove pythonlib entirely, remove deprecated modules, and do something reasonable with the authentication.

**Comment by KevinGoodsell** [comment]
The version of TMDA here is now identical to the upstream version, and tmda-cgi is supported (though not guaranteed to be entirely working). I've tested it a bit and fixed the obvious problems. More testing will be happening in the future. The comment about it being unsupported has been removed from the wiki.
